language: python

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - pip install -r requirements.txt
  - python setup.py install

deploy:
  provider: pypi
  user: pirion
  password:
    secure: VqpnMY6EuIsqII5xnZAmS8ezy+H2mtVdOFnzfryPHyUSjmUQp6DzG2ZcaQqjeyuj89RwCTWgF6p5v/wiP0LAT/zzP83sLkhllgm/v+hES9lPZ2SCWFeT8bQrqrFBhiOdbeViJlBxVMKk4ldFY9qSfCyTOP8T6SvQ9NdJuaYTCzsm3gqUl5tW2mePsbIQW0EcYs2hAkt/4F0kZKg2pIFtsa+hrccejUlG9zQxEBoGD7sDpZNw1N4xU43AnbSHF/S6SJ8kNoa4STrdW+TynKB3x8Ioxpzn2nNckAAUe16RtE3y9n7aTfhsPhSIfp+3Eep6d7c26MexereDeTtyRQVpb7lIQGUkBgJtrjK+/oPrxKzjBbq8EAc08KTmxDef7SZ3EMK4wjZI/s40P2j6rf1lNZoE5UV38dvdpCJ8hBZboCfrkb8wr8y5v4X+QDAdus/8WVmFuFOqkrLkYN1DUtJXIOrT0k3ypR57nCij8ySoRF7REX6FU1YqfoBg10OVD6dIoGzHJ7fUNR+3MWyQXKOnhdR8WLggDTwdA/Ofb8jmp5gHX+8zwrXtbGUpuB2/6W2FhI90TDc+Zij3JZchPS+/JWfQrRDXmNmguM409rszFVjIRQEBCdvQZm0N5rZ+ouR/zzILowlU7DjSY68M3UemF89XQtUMrSQgkOVLpsV2lyk=
  distributions: "sdist bdist_wheel bdist_egg"
  skip_existing: true
  on:
      tags: true

script:
 - echo "Done"