language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install -r requirements.txt
- python setup.py install
deploy:
  provider: pypi
  user: pirion
  password:
    secure: JUNQRpjRZlKufYhdKyPErb2QWVL/Cpc0ZYvVioLX578kaMRbQVw5JXsSy9rkj+gcqFxZ2iPy6rDmIDq/AsUCB2BthOr2n1K0NvPi1cW51FXhh7fWwJYh6vOvZslqDG6bkLCbybOAqhaCZwqsAYwgmgucnB+Ad0J7IcXhqNXiFgutmqZtgvaXvO1ijbU+6IvIoSsHi1nOymIVO5q53iwOiCkiA0gVJ+OGzhig34WXSSebGmgUZlfr9Yyys3xcdvUkO1J26bcKJe/2yElkA68BZ0Pjy80KIX/RNdbduCgreAFI+M7AIWEA1zaS6vkL9ND5eiyqmq5CBCUpAob4UEpD9kFFgEDU7+B2rwyZtHq03m4TD4rFkkWPzjxDYnnsE3FFj3rwZtgBQu1ETKAX3dOKU25EN9LdSCKRqcAglrQEU7IGU3rXhEmdESFZf/yhOnf6m5UGQ56IET4XeEX1jfxHdt4xpm2uctKTJ1JrGdyk+cOPtJD7G3sKHCR/GFriMdTsob/O3H1F41e2TpQEG/C6VOrW4pWFMZ1QCbBTpSvTLVSRhsa3RwxuVGIBUbmtodFnaGvPJtIl7JYmvlvxWDFc8CSCXpFV+d3C/Ya3KY4PWMMrSi4RB+2j/1hMzvK1R4IDLVmEwtX381iXk6DxqvabVxiQasj6GRC7Syo8uug5bnQ=
  distributions: sdist bdist_wheel bdist_egg
  skip_existing: true
  on:
    tags: true
script:
- echo "Done"
